# The base Hydra config

defaults:
  - env: base_env
  - algorithm: base_algorithm
  - evaluation: base_evaluation
  - _self_


exp_name: ???

epochs: 1000
seed: 0



hydra:
  run:
    dir: ./output/hydra/training/${now:%Y-%m-%d}/${exp_name}
  sweep:
    dir: ./output/hydra/training/${now:%Y-%m-%d}
    subdir: ${exp_name}/${sub_dir_shortener:${hydra:job.override_dirname}, 3, False}/seed_${format:${seed}, '{:02d}'}
#    subdir: ${recorder.wandb.group_name}/${recorder.wandb.job_type}/seed_${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed