# The base Hydra config

defaults:
  - env: base_env
  - algorithm: base_algorithm
  - evaluation: base_evaluation
  - _self_


exp_name: ???

epochs: 1000
seed: 0

wandb:
  enabled: True  # whether to use the wandb logger or not
  project_name: CalabiYau  # name of the project
  entity: null  # name of the entity to log to. Will default to your private wandb account
  group_name: ${exp_name}
  run_name: seed_${seed}
  job_type: ${sub_dir_shortener:${hydra:job.override_dirname}, 3, False}
#  job_type: ${hydra:job.override_dirname}
  # only used categorizing wandb projects
  tags: null  # list of custom tags to sort/find these runs by
  start_method: "thread"  # start method for wandb. "thread" is recommended for slurm and on your cluster.
  # null will use the default wandb start method,
  # which is "fork" on linux and "spawn" on windows (according to copilot)



hydra:
  run:
    dir: ./output/hydra/training/${now:%Y-%m-%d}/${exp_name}
  sweep:
    dir: ./output/hydra/training/${now:%Y-%m-%d}
    subdir: ${exp_name}/${sub_dir_shortener:${hydra:job.override_dirname}, 3, False}/seed_${format:${seed}, '{:02d}'}
#    subdir: ${recorder.wandb.group_name}/${recorder.wandb.job_type}/seed_${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed